name: Send email on push

on:
  push:
    branches:
      - main

jobs:
  send mail:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Push Notification for ${{ github.repository }}"
          to: "miljukovad@gmail.com"
          body: |
            A push was made to the repository: ${{ github.repository }}
            Commit message: ${{ github.event.head_commit.message }}
            Pushed by: ${{ github.event.pusher.name }}
          from: Github actions

          